<div id="help">
<h1 class="h1help">Keterangan Field</h1>

<table>
  <tr>
	<td>
	  <strong>Nama Field</strong>
	</td>
	<td>
	  <strong>Jenis Field</strong>
	</td>
	<td>
	  <strong>Keterangan</strong>
	</td>
  </tr>
  <tr>
	<td>
	  Onleave Name
	</td>
	<td>
	  Karakter, A-Z, a-z
	</td>
	<td>
	  Nama Jenis Cuti
	</td>
  </tr>
  <tr>
	<td>
	  Day Max
	</td>
	<td>
	  Angka, 0-9
	</td>
	<td>
	  Jumlah maksimum hari
	</td>
  </tr>
  <tr>
	<td>
	  Start Day
	</td>
	<td>
	  Angka, 0-9
	</td>
	<td>
	  Jumlah hari dimana karyawan diperbolehkan cuti
	</td>
  </tr>
  <tr>
	<td>
	  SNRO (Specific Number Range Object)
	</td>
	<td>
    Pilihan, dari modul <a href="index.php?r=snro/index">SNRO</a>
	</td>
	<td>
	  Format No Dokumen, generated by system
	</td>
  </tr>
  <tr>
	<td>
	  Absence Statues
	</td>
	<td>
    Pilihan, dari modul <a href="index.php?r=absstatus/index">Absence Statues</a>
	</td>
	<td>
	  Format No Dokumen, generated by system
	</td>
  </tr>
  <tr>
	<td>
	  Record Status
	</td>
	<td>
	  checkbox
	</td>
	<td>
	  Status aktif (check) / tidak (uncheck)
	</td>
  </tr>
</table>
</div>

